version: '3.9'

volumes:
  postgres_data:

services:
  postgres:
    image:  postgres:13.3
    ports:
      - 35432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:  root
      POSTGRES_PASSWORD:  root
      POSTGRES_DB: schedule_notifier